const INVALID_TOKEN_VALIDATION = 'INVALID_TOKEN_VALIDATION';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const INVALID_PUBLICKEY = 'INVALID_PUBLICKEY';
const NO_PUBLICKEY = 'NO_PUBLICKEY';
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const BAD_TOKEN = 'BAD_TOKEN';

module.exports = {
    INVALID_TOKEN_VALIDATION,
    INVALID_CREDENTIALS,
    INVALID_PUBLICKEY,
    NO_PUBLICKEY,
    USER_NOT_FOUND,
    BAD_TOKEN
}