const INVALID_TOKEN_VALIDATION = 'INVALID_TOKEN_VALIDATION';
const INVALID_TOKEN_VALIDATION_DESCRIPTION = 'Invalid validation code';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const INVALID_CREDENTIALS_DESCRIPTION = 'Auth key is not valid';
const INVALID_PUBLICKEY = 'INVALID_PUBLICKEY';
const INVALID_PUBLICKEY_DESCRIPTION = 'Not a valid RSA Public Key';
const PERSON_NOT_ALLOWED = 'PERSON_NOT_ALLOWED';
const PERSON_NOT_ALLOWED_DESCRIPTION = 'isAllowed = false';

module.exports = {
    INVALID_TOKEN_VALIDATION,
    INVALID_TOKEN_VALIDATION_DESCRIPTION,
    INVALID_CREDENTIALS,
    INVALID_CREDENTIALS_DESCRIPTION,
    INVALID_PUBLICKEY,
    INVALID_PUBLICKEY_DESCRIPTION,
    PERSON_NOT_ALLOWED,
    PERSON_NOT_ALLOWED_DESCRIPTION
}